### ISSUE TITLE
`serde_yaml::Value` does not perfectly round trip serialize. 

### ISSUE THREAD

**Issue by doug-q** [CQCL/hugr#1048]
In paticular https://docs.rs/serde_yaml/latest/serde_yaml/value/struct.TaggedValue.html is deserialized as a `Mapping`. Observe this by uncommenting the generator in `crate::proptest::any_serde_value` (currently in review #981).

Ideas:
* use `serde_json::Value` for our "opaque" representation in `CustomSerialized`, `CustomTypeArg`, etc. we already use `serde_json::Value` for metadata.
* Fail to serialize `TaggedValue`s.
* Try to fix the round trip.

**Comment by zrho** [comment]
What is the current state of discussion with respect to YAML? If we are moving to JSON (or at least away from YAML) anyway, there would be nothing to do for this issue.

Tagged values are a really nice feature of YAML that is unfortunately missing in JSON. Therefore JSON formats always have to make up their own encoding of tags, and there isn't a universally agreed upon way to do this. Msgpack has extensions, but they are not quite the same as tagged values, and there does not appear to be an standardised extension for tagged values. Therefore msgpack would do a similar encoding as JSON.

The Rust ecosystem of YAML libraries is in an unfortunate state. In particular, the `serde_yaml` crate is no longer maintained, marked as deprecated on crates.io and the repository is archived.

There is an additional option: Use a custom `Value` type which serialises and deserialises cleanly to JSON and msgpack, but otherwise maps more directly onto the sort of data that we deal with. I might, for instance, want to have metadata consisting of a type, or type scheme, or type row, etc.
