### ISSUE TITLE
Add "requires binary" flag to opdef signatures.

### ISSUE THREAD

**Issue by ss2165** [CQCL/hugr#1361]
Operations in Extension declarations can state one of:
- An explicit type scheme 
- A type scheme + a flag indicating binary required for validation, in-memory extensions should point to this function.
- A flag indicating code required to compute the type scheme, in-memory extensions should point to this function.

**Comment by acl-cqc** [comment]
How do I interpret this? Does this describe the current situation, or the desired state? If the latter, which bits are new?

Looking at the current `op_def.rs`, I note we use `struct CustomValidator` for every case where we have a PolyFuncType, even if there is no custom binary code - that seems undesirable, and the name is misleading (CustomValidator does not necessarily include any custom validation code!). I'd suggest:
```
pub enum SignatureFunc {
  //PolyFuncType(CustomValidator) // i.e., remove this, replace with:
  PolyFuncType(PolyFuncTypeRV, Option<Box<dyn ValidateTypeArgs>>),
 CustomFunc(Box<dyn CustomSignatureFunc>) // unchanged
}
```
However not clear how this relates to the issue here. A second possible goal is to replace each of the `Box<dyn>`s with an Option where None means "binary code require but absent", which is distinct from a None custom-validation (no validation required)....

**Comment by acl-cqc** [comment]
Ah, or does this just relate to serialization format?

**Comment by ss2165** [comment]
this relates to just serialised yeah, I've been thinking of those as "declarations" (as opposed to "definitions" that may be backed by executable code)
