### ISSUE TITLE
No way to condition on a sum of types that are not tuples

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/hugr#835]
Suppose we have a node that outputs a sum type `Sum(T1, T2)`, and we want to then perform a `Conditional` operation depending on whether it's `T1` or `T2`: either `Case1(T1-->T3)` or `Case2(T2-->T3)`. Now the `Conditional` requires a `TupleSum` as input, i.e. `Sum((Tuple(T1), Tuple(T2))`. However there is currently no way to convert `Sum(T1, T2)` to `Sum((Tuple(T1), Tuple(T2))`.

A couple of options:

* Define a Prelude type such as `UnarySum` with associated operation `to_sum(U: UnarySum<A, B, ...>) ->  Sum<(A,), (B,),...>`.
* Make `Conditional` nodes have arbitrary sum types as input; `Case` nodes have a single input (which may be a tuple that gets unpacked inside the `Case` node.

If we do the second of these, there is the further question whether to make a similar change for `TailLoop` and `CFG` nodes.

**Comment by doug-q** [comment]
I've prototyped the second option here: https://github.com/CQCL/hugr/pull/844

This makes clear an ergonomic disadvantage to abandoning TupleRows: You end up with unit tuples that you have to ignore. See for example [src/builder/tail_loop.rs](https://github.com/CQCL/hugr/pull/844/files#diff-36df3ff21c38d9981ce26ccfd1693f92b2ffee60f69cbbab8fffb991a867e8be).|

> Define a Prelude type such as UnarySum with associated operation to_sum(U: UnarySum<A, B, ...>) ->  Sum<(A,), (B,),...>.

I find this solution ugly and ad-hoc. If B is already a tuple type, I would prefer to apply the "tuplisation" to only A. 

Another option is to change a Sum type so that it holds  a list of TypeRows rather than a list of Types, i.e. ALL sums are tuple sums. This would require changing `tag`: either it accepts a tuple, or it accepts multiple args and implicitly tuples them up.

**Comment by aborgna-q** [comment]
#860 removed the non-tuple variants on sum types.
Can we close this issue now?

**Comment by cqc-alec** [comment]
> #860 removed the non-tuple variants on sum types. Can we close this issue now?

I think so.
