### ISSUE TITLE
Builder errors should make it easier to track down where the error occured

### ISSUE THREAD

**Issue by ss2165** [CQCL/hugr#847]
For example `NoCopyLinear` has no indication of the error location.

More generally its hard to localise an error in the builder without visualisation - some though needs to be put in to this.

**Comment by aborgna-q** [comment]
In general, users `.unwrap()` the result of a builder.
This causes a panic if any error is found, but the printed message is the (often noisy) `Debug` output of the error.

Perhaps some operations should panic instead of returning a result (all the `add_*` methods?).
Failing the validation is probably a bug rather than a user error.

**Comment by qartik** [comment]
> Perhaps some operations should panic instead of returning a result (all the `add_*` methods?).

Agreed! If the error can be found with unwrap, panicking early certainly seems better.

**Comment by aborgna-q** [comment]
#873 was a step toward this, as well as the PRs that made some methods infallible (#872, #869).

I think the next step will be to make `DFGBuilder::create_with_io` infallible (since it never returns an `Err`), and modify the related errors to give more specific context.

**Comment by aborgna-q** [comment]
Marking as completed after the previous comment's PRs.
There is still improvements to be done, but they should go on their own better-defined issues.
