### ISSUE TITLE
Introduce Panic op

### ISSUE THREAD

**Issue by croyzor** [CQCL/hugr#915]
Currently `panic` is a function defined in prelude. Change it to an op which can have any inputs and any outputs. 

This allows linear values to be consumed by `panic` in error code-paths, as well as provides vales to satisfy any local obligations(i.e. you have to wire something to the output node of parent of panic).

**Comment by ss2165** [comment]
Should the linear values be explicitly discarded first?

**Comment by croyzor** [comment]
I think something in the prelude `discard: forall T: Type(Any). T -> ()` would be better for hugr than a qubit specific one. If we add it, a tket2 "qubit discard" method could just be discard `TypeApply`'d to Qubit type

**Comment by cqc-alec** [comment]
I've come to realize that I don't know what panic is. It seems odd for it to be a dataflow op with inputs and outputs, since it does not really have either (or at best, it has a single input message). According to the [spec](https://github.com/CQCL/hugr/blob/main/specification/hugr.md#panic), "any operation may panic". This suggests that it is not actually a node of the graph, but a part of the semantics of all (operation) nodes.

In this view, there is no problem with linear values not being consumed by it, since it isn't part of the DAG.

**Comment by cqc-alec** [comment]
> This is true, but it is also true that `panic` is specified as a function in the standard library which always panics, intended to be called when you have no better option(e.g. a `Case` which can never happen, but which you are still required to provide). This function is not so useful: your graph will be invalid unless you deal with all linear values and send the right types to the output node.

Thanks, that clarifies the issue for me!
